export const siteConfig = {
  name: "진짜그림",
  title: "진짜그림 | AI 일러스트 검사와 이미지 판별",
  description:
    "진짜그림은 AI 생성 의심 일러스트, 메타데이터, 국소 영역 신호를 함께 분석해 창작 이미지와 공모전 출품작을 빠르게 검토할 수 있도록 돕는 AI 일러스트 검사 서비스입니다.",
  url: "https://realillust.com",
  domain: "realillust.com",
  contactEmail: "team.minswon@gmail.com",
  keywords: [
    "진짜그림",
    "AI 일러스트 검사",
    "AI 일러스트 판별",
    "AI 생성 일러스트 검사",
    "일러스트 AI 검사",
    "일러스트 AI 판별",
    "AI 이미지 검사",
    "AI 이미지 판별",
    "AI 그림 검사",
    "AI 그림 판별",
    "AI 이미지 탐지",
    "AI 이미지 감지기",
    "AI 생성 이미지 검사",
    "일러스트 공모전 AI 검사",
    "일러스트 공모전 AI 확인",
    "공모전 AI 일러스트 검사",
    "공모전 AI 그림 검사",
    "디자인 공모전 AI 검증",
    "이미지 메타데이터 분석",
    "국소 영역 탐지",
    "일러스트 검토",
  ],
} as const;
