export const siteConfig = {
  name: "HeyMoa",
  title: "HeyMoa | 참여형 AI 회의 운영 에이전트",
  description:
    "HeyMoa는 회의 대화를 기록하고 맥락과 결정사항을 요약하며, 담당자별 액션 아이템을 정리해 후속 업무로 연결하는 AI 회의 운영 서비스입니다.",
  url: "https://heymoa.app",
  domain: "heymoa.app",
  contactEmail: "team.minswon@gmail.com",
  keywords: [
    "HeyMoa",
    "heymoa",
    "Hey Moa",
    "hey moa",
    "헤이모아",
    "헤이 모아",
    "AI 회의",
    "AI Agent",
    "회의 기록",
    "참여형 AI",
    "액션 아이템",
    "회의 운영",
    "회의 에이전트",
    "업무 자동화",
  ],
} as const;
